name: Build and push container images to Quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'

jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "3.8/Dockerfile"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
            image_name: "python-38-centos7"
          - dockerfile: "3.9-minimal/Dockerfile.rhel8"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "el8"
            image_name: "python-39-minimal-el8"
          - dockerfile: "3.10/Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "310"
            image_name: "python-310"
    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          tag: ${{ matrix.tag }}
          image_name: ${{ matrix.image_name }}
